apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aks-hello-world
  template:
    metadata:
      labels:
        name: aks-hello-world
    spec:
      containers:
        - name: aks-hello-world
          image: ${APP_IMAGE}
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - name: app
              containerPort: 8080
            - name: health
              containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: aks-hello-world
spec:
  type: ClusterIP
  ports:
    - name: app
      port: 80
      targetPort: 8080
    - name: health
      port: 8081
  selector:
    name: aks-hello-world
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aks-hello-world
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: aks-hello-world.${DNS_ZONE}
      http:
        paths:
          - path: /
            backend:
              serviceName: aks-hello-world
              servicePort: 80
          - path: /healthcheck
            backend:
              serviceName: aks-hello-world
              servicePort: 8081
